trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm i -g gulp-cli@latest verbose/verb#dev verb-generate-readme lerna
  displayName: 'sudo npm'
